### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tav** [tav/xnet#1]
## Overview

The xnet was a collaboration platform that powered the early Espian iterations:

&nbsp;&nbsp;&nbsp; <img src="https://cloud.githubusercontent.com/assets/30302/6316449/c4c472fe-ba1e-11e4-8816-aed77fe7c4e1.jpg" width="40%" height="40%"> &nbsp;&nbsp;&nbsp; <img src="https://cloud.githubusercontent.com/assets/30302/6316447/a67be1ba-ba1e-11e4-98d6-7b1388d667a4.jpg" width="40%" height="40%">

The aim for the new xnet is to provide an equivalent collaboration platform for our needs today, and to act as an effective tool to support the Million Dollar WikiHouse campaign.

#### Devops

* [x] Setup a GitHub repo for xnet.

* [ ] Setup an EC2 account.

* [ ] Setup an App Engine app.

* [ ] Purchase an SSL certificate for `espians.com` and `www.espians.com`.

#### Frontend

- [ ] Redirect requests to the `www` subdomain to the apex domain.

#### Campaign Content

- [ ] Campaign Landing Page.

- [ ] Innovation Streams Pages.

- [ ] Header Animation.

- [ ] Images.

- [ ] Credits Page.

- [ ] FAQ.

- [ ] Press Pack.

#### Blog Posts

- [ ] Why We Need an Open Platform for Open Hardware.

- [ ] Beyond Patents & Liability: The Need for a Creative Commons Unlicense.

#### Initiatives

Categorised as either an Open, Income, or Executive Initiative:

- [ ] Ampify.

- [ ] AmpOS.

- [ ] Ampserv.

- [ ] Espra.

- [ ] Holoband.

- [ ] MatchDB.

- [ ] Million Dollar WikiHouse.

- [ ] Naaga.

- [ ] Podnet.

- [ ] ReviewTool.

- [ ] Toman.

- [ ] WikiDesign.

- [ ] WikiHouse.

#### Other Content

- [ ] Espians Homepage.

    > We are building the tools for the future of production.

- [ ] Espians About Page.

- [ ] AskTav Blog — fix up old content and redirect to https://espians.com/~tav.

#### Social Media

- [ ] Facebook: @Espians.

- [ ] Facebook: @tav.

- [ ] GitHub: @Espians.

- [ ] GitHub: @tav.

- [ ] LinkedIn: @Espians.

- [ ] LinkedIn: @tav.

- [ ] Twitter: @Espians.

- [ ] Twitter: @tav.

#### Finance

- [ ] Partnership Tax Return.

- [ ] Business Bank Account: Euro/Dollar Accounts.

- [ ] VAT Return.

#### Personal

- [ ] HMRC.

- [ ] Update all passwords.

- [ ] Enable 2FA wherever possible.
